# Generated by Django 5.0.4 on 2024-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('inprogress', 'In Progress'), ('complete', 'Complete')], default='todo', max_length=10),
        ),
    ]
